### ISSUE TITLE
Hosts 翻墙中移动设备翻墙一段的补充

### ISSUE THREAD

**Issue by ChenyeJin** [gfw-breaker/i-break-gfw#1]
所有的Linux基础的设备，在root用户登录下，修改/etc/下的hosts即可。
Android设备适用，测试版本: 原生2.3.5、4.0.3、6.0.1、8.0可用，其他版本大概率可用，替换后需要重启或开关飞行模式
Arch、Gentoo、Ubuntu、Debian、Deepin可用，需要手动重置对应发行版的网络管理器
MacOS同理可用，但重置方法稍有不同。
没有iOS设备，无法测试/了解，按理来说是不行的。我猜越狱了也不行。

**Comment by gfw-breaker** [comment]
@ChenyeJin 谢谢补充，Android通过什么工具登录修改呢？

**Comment by ChenyeJin** [comment]
通过有Root权限的文件管理器，例如Root Explorer、Cyanogen文件管理器、ES文件管理器等
